---
# ================================================================
# 1. Section: IDENTIFIERS
# ================================================================
mouse: 32B
data_folder: data
tissue_type: TissueType.SPINAL_COORD
description: ""

# ================================================================
# 2. Section: ZARR LOADING
# ================================================================
drive_root: /Volumes/GuiNR
zarr_path: Transfer/561_CFos_raw.zarr

# ================================================================
# 3. Section: PREPROCESSING
# ================================================================
smooth_centerline_window: 25

untwist_registration:
  MetricConfig:
    name: CC
    sampling_percentage: 1
    histogram_bins: 50
  OptimizerConfig:
    name: GD
    iterations: 500
    learning_rate: 0.01
    convergence_minimum_value: 1e-8
    convergence_window_size: 30
    gradient_convergence_tolerance: 1e-8
    maximum_number_corrections: 5
    estimate_learning_rate: 2
    max_step_size_physical_units: 1.0
    grid_size: 2
    constrains: []
    scales: []
    initial_angle: None
    initial_fixed_parameters: None
    initial_parameters: None
  InterpolationConfig:
    registration: bspline
    resampling: linear
  MultipleResolutionConfig:
    enabled: False
    shrink_factors: [4, 2, 1]
    smoothing_sigmas: [2, 1, 0]

# ================================================================
# 4. Section: ATLAS REGISTRATION
# ================================================================
max_retries: 5

atlas_affine_registration:
  MetricConfig:
    name: MI
    sampling_percentage: 1
    histogram_bins: 50
  OptimizerConfig:
    name: GD
    iterations: 5000
    learning_rate: 0.01
    convergence_minimum_value: 1e-8
    convergence_window_size: 25
    gradient_convergence_tolerance: 1e-8
    maximum_number_corrections: 5
    estimate_learning_rate: 0
    max_step_size_physical_units: 1.0
    grid_size: 2
    constrains: []
    scales: []
    initial_angle: None
    initial_fixed_parameters: None
    initial_parameters: None
  InterpolationConfig:
    registration: bspline
    resampling: nearest
  MultipleResolutionConfig:
    enabled: False
    shrink_factors: [4, 2, 1]
    smoothing_sigmas: [2, 1, 0]

atlas_warp_registration:
  MetricConfig:
    name: MI
    sampling_percentage: 1
    histogram_bins: 50
  OptimizerConfig:
    name: GD
    iterations: 500
    learning_rate: 0.01
    convergence_minimum_value: 1e-12
    convergence_window_size: 50
    gradient_convergence_tolerance: 1e-8
    maximum_number_corrections: 5
    estimate_learning_rate: 1
    max_step_size_physical_units: 1.0
    grid_size: 2
    constrains: []
    scales: []
    initial_angle: None
    initial_fixed_parameters: None
    initial_parameters: None
  InterpolationConfig:
    registration: linear
    resampling: nearest
  MultipleResolutionConfig:
    enabled: True
    shrink_factors: [4, 2, 1]
    smoothing_sigmas: [2, 1, 0]

# ================================================================
# 5. Section: POST-REGISTRATION
# ================================================================
background_label: 0
